name: Test Custom Code

on:
  workflow_run:
    workflows: ["Deliver container"]
    types:
      - completed

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker Container Locally
        run: docker run -d -p 8000:8000 kunocls/api-final

      - name: Run Tests Locally
        run: |
          pip install pytest
          pytest app/test_Events.py
        continue-on-error: true
